name: Deploy Nest.js Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /var/www/html/backend.linchpin.exir || exit 1
            
            # Ensure the correct SSH key is used for Git
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id_rsa
            
            # Pull latest code
            git fetch origin main
            git reset --hard origin/main
            
            # Install dependencies
            npm install
            
            # Build the project
            npm run build
            
            # Restart the NestJS app using PM2
            pm2 restart nestjs-app || pm2 start dist/main.js --name "nestjs-app"
            pm2 save
            pm2 startup
