name: Deploy Nest.js Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create the .ssh directory if it doesn't exist
            mkdir -p ~/.ssh

            # Add the private SSH key to the SSH agent
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            # Add GitHub's SSH host key to known_hosts to prevent the "Host key verification failed" error
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            # Ensure SSH agent is running and add the private key
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa

            # Test SSH connection to GitHub (debugging step)
            ssh -vT git@github.com

            # Change Git remote URL from HTTPS to SSH
            git remote set-url origin git@github.com:Exir-world/backend.linchpin.exir.git

            # Fetch the latest changes and reset to avoid merge issues
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies and build the project
            npm install
            npm run build

            # Restart the NestJS app using PM2
            pm2 restart backend-linchpin || pm2 start dist/main.js --name "backend-linchpin"
            pm2 save
            pm2 startup
